name: Build Markdown using GitHub Actions

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: setup LaTex environment
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-extra-utils texlive-latex-extra

    - name: convert MarkDown to PDF
      run: pandoc sample.md -o sample-markdown-2-pdf.pdf --pdf-engine=xelatex

    - name: Upload compiled PDF
      uses: actions/upload-artifact@v4
      with:
        name: mardown-2-pdf
        path: sample.pdf
    